# Generated by Django 3.2.14 on 2022-11-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase_expense',
            name='destinofsupply',
        ),
        migrations.RemoveField(
            model_name='purchase_expense',
            name='gsttype',
        ),
        migrations.AddField(
            model_name='itemtable',
            name='itmdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchasebill_item',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='vendor_statment',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='stock',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill_item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit1',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='vendor_payment',
            fields=[
                ('vendorpymid', models.AutoField(primary_key=True, serialize=False, verbose_name='CUSTPYMID')),
                ('vendor', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('amount_received', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('paid_through', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100, null=True)),
                ('account', models.CharField(max_length=100, null=True)),
                ('des', models.CharField(max_length=100, null=True)),
                ('running_bal', models.CharField(max_length=100)),
                ('accounts1id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='item_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=255)),
                ('qtyin', models.IntegerField(blank=True, null=True)),
                ('qtyout', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('bitm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('ditm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasedebit1')),
                ('initm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice_item')),
                ('itm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.itemtable')),
            ],
        ),
        migrations.CreateModel(
            name='expense_banking',
            fields=[
                ('expenseid', models.AutoField(primary_key=True, serialize=False, verbose_name='exid')),
                ('date', models.DateField(null=True)),
                ('expenseaccount', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(default='default.png', upload_to='purchase/expense')),
                ('running_bal', models.CharField(max_length=100)),
                ('accounts1id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='customer_payment',
            fields=[
                ('customerpymid', models.AutoField(primary_key=True, serialize=False, verbose_name='CUSTPYMID')),
                ('customer', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('amount_received', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('received_through', models.CharField(max_length=100)),
                ('paym_ref_no', models.CharField(max_length=100)),
                ('bnk_ref_no', models.CharField(max_length=100)),
                ('file', models.FileField(default='default.jpg', upload_to='Customer')),
                ('des', models.CharField(max_length=100, null=True)),
                ('running_bal', models.CharField(max_length=100)),
                ('accounts1id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
