# Generated by Django 3.2.14 on 2022-12-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20221128_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gstno',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditperiod',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchase_expense',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='cgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='igst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='sgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit1',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchaseorder_item',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchasepayment1',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grandtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='tcs_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='profit_loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255, null=True)),
                ('transactions', models.CharField(max_length=255, null=True)),
                ('acctype', models.CharField(max_length=100, null=True)),
                ('accname', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('details0', models.CharField(max_length=255, null=True)),
                ('details1', models.CharField(blank=True, max_length=255, null=True)),
                ('details2', models.CharField(blank=True, default='', max_length=255)),
                ('payments', models.FloatField(blank=True, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('expnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchase_expense')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice')),
                ('pbill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
                ('pdebit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasedebit')),
            ],
        ),
        migrations.CreateModel(
            name='balance_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100, null=True)),
                ('acctype', models.CharField(max_length=100, null=True)),
                ('account', models.CharField(max_length=100, null=True)),
                ('transactions', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('details1', models.CharField(blank=True, max_length=255, null=True)),
                ('details2', models.CharField(blank=True, default='', max_length=255)),
                ('payments', models.FloatField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
                ('bill_pymnt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasepayment')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('debit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasedebit')),
                ('expnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchase_expense')),
                ('inv_pymnt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment')),
                ('invc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice')),
            ],
        ),
    ]
