# Generated by Django 3.2.14 on 2023-01-07 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_auto_20221223_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('transactions', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('details1', models.CharField(blank=True, default='', max_length=100)),
                ('stocks', models.CharField(blank=True, max_length=100)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('debit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasedebit')),
                ('inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockadjust')),
            ],
        ),
        migrations.CreateModel(
            name='Otp_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_psw', models.IntegerField()),
                ('user_ckeck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemtable',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
