# Generated by Django 3.2.14 on 2023-01-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230107_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp_password',
        ),
    ]
