# Generated by Django 3.2.14 on 2023-01-14 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_delete_otp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='deliver_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='deliver_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Otp_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_psw', models.IntegerField()),
                ('user_ckeck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
