# Generated by Django 3.2.14 on 2023-01-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20230114_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='payments1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profit_loss',
            name='payments1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='status',
            field=models.CharField(default='Draft', max_length=100),
        ),
    ]
