# Generated by Django 3.2.14 on 2023-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_recurring_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
