# Generated by Django 3.2.14 on 2023-06-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_challan_challanitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challanitem',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='challanitem',
            name='dl',
        ),
        migrations.DeleteModel(
            name='challan',
        ),
        migrations.DeleteModel(
            name='challanitem',
        ),
    ]
