# Generated by Django 3.2.14 on 2023-07-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_challan_challanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('types', models.CharField(choices=[('Sales', 'Sales'), ('Purchase', 'Purchase')], default='Sales', max_length=10)),
                ('item_rate', models.CharField(choices=[('percentage', 'Markup or Markdown the item rates by a percentage'), ('individual_rate', 'Enter the rate individually for each item')], default='percentage', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='Indian Rupee', max_length=255)),
                ('upordown', models.CharField(default='Markup', max_length=100)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('roundoffto', models.CharField(default='Never mind', max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='pricelist_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=100, null=True)),
                ('itemrate', models.IntegerField(blank=True, default=0, null=True)),
                ('customrate', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('pricelist1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pricelist')),
            ],
        ),
    ]
