# Generated by Django 3.2.14 on 2023-07-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_pricelist_pricelist_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='roundoffto',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='upordown',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
