# Generated by Django 4.1.7 on 2023-08-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20230706_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='opening_balance_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10),
        ),
    ]
