# Generated by Django 4.1.7 on 2023-08-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_vendor_opening_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='opening_balance_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
