# Generated by Django 4.1.7 on 2023-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_vendor_opening_balance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='attachment',
            field=models.ImageField(null=True, upload_to='vendor-files/'),
        ),
    ]
