# Generated by Django 4.1.7 on 2023-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_purchasebill_vendor_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill_item',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
