# Generated by Django 4.1.7 on 2023-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_purchasebill_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='balance_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='ship_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='total_discount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
