# Generated by Django 4.1.7 on 2023-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_purchasebill_balance_amount_purchasebill_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Billed', 'Billed')], default='Billed', max_length=150),
        ),
    ]
