# Generated by Django 4.1.7 on 2023-09-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_purchaseorder_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_mail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
