# Generated by Django 4.1.7 on 2023-09-13 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_purchaseorder_vendor_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankings_G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=100)),
                ('ifsccode', models.CharField(max_length=20)),
                ('branchname', models.CharField(max_length=100)),
                ('openingbalance', models.IntegerField()),
                ('date', models.DateField()),
                ('balance', models.IntegerField(default=0)),
                ('cash_balance', models.IntegerField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
